### PR TITLE
Added HidePowerShell param

### PR DESCRIPTION
**Pull request by nickrod518**
Added HidePowerShell param. Altered some spacing and capitalization for consistent formatting. Commented out import of ps1xml file that was causing import-module to fail.

### CODE REVIEW

**Comment by 1RedOne** [comment]
I'm very happy that you decided to tackle this one.  so much fun to have a lot of people working on a project!

First off, I removed a few files that weren't needed, could you do a sync and then drop your files back in so I can merge this (my git skills...they're not sufficient enough to tdo this on my own!)  I'm getting merge errors when I try to do approve it now.

When I run this, it still hides the window.  I don't actually see code to spawn the window if the user doesn't provide the `-HidePowerShell` switch, could you point out the line that should do that?

**Comment by nickrod518** [comment]
I'm trying to figure it out on my end but this is literally the first time I've tried to collaborate on something with git. 

The HidePowerShell param is true by default (line 32), and so your code to hide the window will be called unless the user specifies "-HidePowerShell $false" when calling it since your code to hide it is wrapped in an if statement (line 157). Does that answer your question or am I misunderstanding?

**Comment by nickrod518** [comment]
I went overboard with capitalization and tabbing consistency changes and I will gladly remove them all if you want. Also, I changed the param from a bool to a switch because I think that's a little easier to use, but can change that back to a bool as well. (from "-HidePowerShell $false" to "-DontHidePowerShell")

**Comment by 1RedOne** [comment]
Beautifully done!  I'm sorry I borked things so badly and made so much work for you!  I love it, :white_check_mark:  approved!  Merging.

**Pull request merged**
